### ISSUE TITLE
Switch http error code from 500 to 404 if no resource found

### ISSUE THREAD

**Issue by artemlazarev** [artipie/artipie#126] opened 2020-05-10 12:10 UTC
If we will try to get resource from unconfigured storage, we will receive http 500. But according http logic we must recieve http 404.

**Comment by 0crat** [comment] 2020-05-10 12:10
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2020-05-12 08:51
@artemlazarev it's a duplicate of https://github.com/artipie/artipie/issues/74

**Closed by g4s8** 2020-05-12 08:51 UTC
Labels: duplicate
