### ISSUE TITLE
Vertx context warning on each request

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#81] opened 2020-04-17 18:02 UTC
Artipie prints this warning on each incoming HTTP request:
```
WARNING: You're already on a Vert.x context, are you sure you want to create a new Vertx instance?
```
It seems we're creating new Vertx instance for storage on each request.

**Comment by 0crat** [comment] 2020-04-17 18:23
The job [#81](https://github.com/artipie/artipie/issues/81) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b7a6dc0e-e11d-428b-a6e7-ccb5e93bda0f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by Sammers21** [comment] 2020-04-17 21:17
@g4s8, can you provide steps to reproduce it?

**Comment by g4s8** [comment] 2020-04-20 06:22
> @g4s8, can you provide steps to reproduce it?

@Sammers21 steps to reproduce:
 - start Docker image with Artipie and any configured repository (e.g. files)
 - send multiple requests to Artipie (doesn't matter GET or PUT)

The warning will be logged on each request.

**Comment by Sammers21** [comment] 2020-04-20 06:42
@g4s8, Can you provide particular steps(a bash script which starts artipie as a docker container and sends a request)? I'm not able to reproduce it just from your words:

![image](https://user-images.githubusercontent.com/16746106/79721526-29e4b000-82eb-11ea-944c-aa46e7850840.png)

**Comment by g4s8** [comment] 2020-04-20 06:48
@Sammers21 
 1. pull latest commit from master branch of `artipie/artipie` using `git pull` command
 2. build docker image with `docker build -t artipie:local .`
 3. create configuration file and repository directory:
     config file `/tmp/artipie/file.yaml`:
```yaml
repo:
  type: file
  storage:
    type: fs
    path: /var/artipie/file
```
and directory: `mkdir -pv /tmp/artipie/file`
  4. run docker image: `docker run -v /tmp/artipie:/var/artipie -p80:80 artipie:local`
  5. send multiple requests to this server: `http PUT localhost/file/hello hello=world`

**Comment by Sammers21** [comment] 2020-04-20 07:13
@g4s8, I did as you say. Still can't reproduce:
![image](https://user-images.githubusercontent.com/16746106/79724056-906bcd00-82ef-11ea-8749-2e49896e6b07.png)

**Comment by g4s8** [comment] 2020-04-20 07:45
@Sammers21 I mistyped the path, config file should be located at `/tmp/artipie/repo/file.yaml`

**Comment by Sammers21** [comment] 2020-04-20 09:29
@g4s8, I have successfully reproduced the problem.

**Closed** 2020-04-20 11:12 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-04-22 18:51
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment] 2020-04-23 09:55
@0crat out

**Comment by 0crat** [comment] 2020-04-23 12:27
> @0crat out ([here](https://github.com/artipie/artipie/issues/81#issuecomment-618304868))

@g4s8 Job [#81](https://github.com/artipie/artipie/issues/81) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't set title

**Comment by 0crat** [comment] 2020-04-23 13:54
> @0crat out ([here](https://github.com/artipie/artipie/issues/81#issuecomment-618304868))

@g4s8 Job [#81](https://github.com/artipie/artipie/issues/81) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't set title

**Comment by 0crat** [comment] 2020-04-23 13:55
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sammers21[/z](https://www.0crat.com/u/sammers21), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment] 2020-04-23 13:56
@0crat quality good

**Comment by 0crat** [comment] 2020-04-23 14:17
> @0crat out ([here](https://github.com/artipie/artipie/issues/81#issuecomment-618304868))

@g4s8 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c08ec908-6891-4027-9aad-79415e47ffee, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.scope.wbs.remove_label_from_github_ticket
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.53.11](https://github.com/zerocracy/farm): CID: [d9080469-f023-485e-8545-02fc68ccdadf](https://www.0crat.com/footprint/CT2E6TK9B/d9080469-f023-485e-8545-02fc68ccdadf), Type: "Job removed from WBS"
