### ISSUE TITLE
Get rid of properties

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#42] opened 2020-03-12 11:40 UTC
For now, properties are passed in the following way:
```
-Dartipie.storage=./config.yml -Dartipie.port=8080
```
That is not gonna work in case is compiled as a native image. We should move to command line args

**Comment by 0crat** [comment] 2020-03-12 11:40
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2020-03-12 12:13
@Sammers21 it's a duplicate of #32

**Closed by g4s8** 2020-03-12 12:13 UTC
Labels: duplicate

**Comment by 0crat** [comment] 2020-03-12 15:17
Job `gh:artipie/artipie#42` is not assigned, can't get performer
