### ISSUE TITLE
Upload request limits

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#119] opened 2020-05-08 06:39 UTC
We need to have an option to limit upload requests size by configuring Artipie server. E.g. we may use optional configuration parameter in server yaml config or environment variable and filter incoming requests by `Content-Length` header and reject big requests on upload by returning `400` or [413](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413).

**Comment by 0crat** [comment] 2020-05-08 06:49
The job [#119](https://github.com/artipie/artipie/issues/119) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fbecedef-2760-4b3c-a020-84f17bc5464d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment] 2020-05-13 08:46
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Closed** 2020-05-14 13:17 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-05-14 13:34
Job [#119](https://github.com/artipie/artipie/issues/119) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment] 2020-05-14 13:34
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @g4s8[/z](https://www.0crat.com/u/g4s8) (its creator); I won't close the order; please, re-open it and ask @g4s8[/z](https://www.0crat.com/u/g4s8) to close it

**Comment by 0crat** [comment] 2020-05-20 01:07
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment] 2020-05-20 06:57
@0crat quality good
