### ISSUE TITLE
NoClassDefFoundError: org/slf4j/event/LoggingEvent

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#155] opened 2020-05-19 14:00 UTC
Configure a gem repo and try to push a gem. You would get this error:

```
$ GEM_HOST_API_KEY=123 gem push builder-3.2.4.gem --host http://localhost:8080/gem
Pushing gem to http://localhost:8080/gem...
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1309)
        at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1276)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
        at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
        at io.reactivex.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onComplete(SingleFlatMapPublisher.java:117)
        at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
        at io.reactivex.internal.operators.flowable.FlowableMergeWithCompletable$MergeWithSubscriber.otherComplete(FlowableMergeWithCompletable.java:120)
        at io.reactivex.internal.operators.flowable.FlowableMergeWithCompletable$MergeWithSubscriber$OtherObserver.onComplete(FlowableMergeWithCompletable.java:147)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
        at com.artipie.asto.fs.RxFile.lambda$null$0(RxFile.java:89)
        at io.vertx.reactivex.core.Future$3.handle(Future.java:190)
        at io.vertx.reactivex.core.Future$3.handle(Future.java:187)
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:159)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:120)
        at io.vertx.reactivex.core.Promise.complete(Promise.java:104)
        at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
        at io.vertx.reactivex.impl.AsyncResultCompletable.lambda$subscribeActual$0(AsyncResultCompletable.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(java/lang/Class.java:3167)
        at java.lang.Class.getDeclaredMethods(java/lang/Class.java:2310)
        at org.jruby.javasupport.binding.MethodGatherer$1.computeValue(org/jruby/javasupport/binding/MethodGatherer.java:256)
        at org.jruby.javasupport.binding.MethodGatherer$1.computeValue(org/jruby/javasupport/binding/MethodGatherer.java:252)
        at java.lang.ClassValue.getFromHashMap(java/lang/ClassValue.java:226)
        at java.lang.ClassValue.getFromBackup(java/lang/ClassValue.java:208)
        at java.lang.ClassValue.get(java/lang/ClassValue.java:114)
        at org.jruby.javasupport.binding.MethodGatherer$2.computeValue(org/jruby/javasupport/binding/MethodGatherer.java:266)
        at org.jruby.javasupport.binding.MethodGatherer$2.computeValue(org/jruby/javasupport/binding/MethodGatherer.java:263)
        at java.lang.ClassValue.getFromHashMap(java/lang/ClassValue.java:226)
        at java.lang.ClassValue.getFromBackup(java/lang/ClassValue.java:208)
        at java.lang.ClassValue.get(java/lang/ClassValue.java:114)
        at org.jruby.javasupport.binding.MethodGatherer.eachAccessibleMethod(org/jruby/javasupport/binding/MethodGatherer.java:176)
        at org.jruby.javasupport.binding.MethodGatherer.getMethods(org/jruby/javasupport/binding/MethodGatherer.java:156)
        at org.jruby.javasupport.binding.MethodGatherer.setupMethods(org/jruby/javasupport/binding/MethodGatherer.java:558)
        at org.jruby.javasupport.binding.MethodGatherer.initialize(org/jruby/javasupport/binding/MethodGatherer.java:127)
        at org.jruby.javasupport.binding.ClassInitializer.initialize(org/jruby/javasupport/binding/ClassInitializer.java:63)
        at org.jruby.javasupport.binding.Initializer.setupProxyClass(org/jruby/javasupport/binding/Initializer.java:54)
        at org.jruby.javasupport.Java.createProxyClass(org/jruby/javasupport/Java.java:549)
        at org.jruby.javasupport.Java.generateClassProxy(org/jruby/javasupport/Java.java:507)
        at org.jruby.javasupport.Java.createProxyClassForClass(org/jruby/javasupport/Java.java:463)
        at org.jruby.javasupport.JavaSupportImpl$3.computeValue(org/jruby/javasupport/JavaSupportImpl.java:127)
        at org.jruby.javasupport.JavaSupportImpl$3.computeValue(org/jruby/javasupport/JavaSupportImpl.java:119)
        at org.jruby.javasupport.JavaSupportImpl.getProxyClassFromCache(org/jruby/javasupport/JavaSupportImpl.java:202)
        at org.jruby.javasupport.Java.getProxyClass(org/jruby/javasupport/Java.java:430)
        at org.jruby.javasupport.Java.getInstance(org/jruby/javasupport/Java.java:357)
        at org.jruby.javasupport.Java.getInstance(org/jruby/javasupport/Java.java:339)
        at org.jruby.javasupport.JavaUtil.convertJavaToUsableRubyObject(org/jruby/javasupport/JavaUtil.java:188)
        at org.jruby.javasupport.JavaMethod.convertReturn(org/jruby/javasupport/JavaMethod.java:518)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:457)
        at org.jruby.javasupport.JavaMethod.invokeStaticDirect(org/jruby/javasupport/JavaMethod.java:368)
        at RUBY.<class:SubmitGem>(<script>:18)
        at RUBY.<main>(<script>:8)
        at org.jruby.Ruby.evalScriptlet(org/jruby/Ruby.java:860)
        at org.jruby.Ruby.evalScriptlet(org/jruby/Ruby.java:836)
        at org.jruby.javasupport.JavaEmbedUtils$2.eval(org/jruby/javasupport/JavaEmbedUtils.java:147)
        at com.artipie.gem.GemSlice.rubyLookUp(com/artipie/gem/GemSlice.java:131)
        at com.artipie.gem.GemSlice.<init>(com/artipie/gem/GemSlice.java:88)
        at com.artipie.gem.GemSlice.<init>(com/artipie/gem/GemSlice.java:70)
        at com.artipie.SliceFromConfig.lambda$build$2(com/artipie/SliceFromConfig.java:92)
        at com.artipie.SliceFromConfig.lambda$build$11(com/artipie/SliceFromConfig.java:127)
        at java.util.concurrent.CompletableFuture.biApply(java/util/concurrent/CompletableFuture.java:1307)
        at java.util.concurrent.CompletableFuture$BiApply.tryFire(java/util/concurrent/CompletableFuture.java:1276)
        at java.util.concurrent.CompletableFuture.postComplete(java/util/concurrent/CompletableFuture.java:506)
        at java.util.concurrent.CompletableFuture.complete(java/util/concurrent/CompletableFuture.java:2144)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(io/reactivex/internal/observers/ConsumerSingleObserver.java:62)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(io/reactivex/internal/operators/single/SingleMap.java:64)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(io/reactivex/internal/operators/single/SingleDoOnSuccess.java:60)
        at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(io/reactivex/internal/operators/flowable/FlowableReduceSeedSingle.java:110)
        at io.reactivex.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onComplete(io/reactivex/internal/operators/single/SingleFlatMapPublisher.java:117)
        at io.reactivex.internal.util.HalfSerializer.onComplete(io/reactivex/internal/util/HalfSerializer.java:90)
        at io.reactivex.internal.operators.flowable.FlowableMergeWithCompletable$MergeWithSubscriber.otherComplete(io/reactivex/internal/operators/flowable/FlowableMergeWithCompletable.java:120)
        at io.reactivex.internal.operators.flowable.FlowableMergeWithCompletable$MergeWithSubscriber$OtherObserver.onComplete(io/reactivex/internal/operators/flowable/FlowableMergeWithCompletable.java:147)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(io/reactivex/internal/operators/completable/CompletableCreate.java:64)
        at com.artipie.asto.fs.RxFile.lambda$null$0(com/artipie/asto/fs/RxFile.java:89)
        at io.vertx.reactivex.core.Future$3.handle(io/vertx/reactivex/core/Future.java:190)
        at io.vertx.reactivex.core.Future$3.handle(io/vertx/reactivex/core/Future.java:187)
        at io.vertx.core.impl.FutureImpl.dispatch(io/vertx/core/impl/FutureImpl.java:107)
        at io.vertx.core.impl.FutureImpl.tryComplete(io/vertx/core/impl/FutureImpl.java:152)
        at io.vertx.core.impl.FutureImpl.tryComplete(io/vertx/core/impl/FutureImpl.java:159)
        at io.vertx.core.impl.FutureImpl.complete(io/vertx/core/impl/FutureImpl.java:120)
        at io.vertx.reactivex.core.Promise.complete(io/vertx/reactivex/core/Promise.java:104)
        at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(io/reactivex/internal/observers/CallbackCompletableObserver.java:53)
        at io.vertx.reactivex.impl.AsyncResultCompletable.lambda$subscribeActual$0(io/vertx/reactivex/impl/AsyncResultCompletable.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(io/vertx/core/impl/ContextImpl.java:330)
        at io.vertx.core.impl.ContextImpl.executeTask(io/vertx/core/impl/ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(io/vertx/core/impl/EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(io/netty/util/concurrent/AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(io/netty/util/concurrent/SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(io/netty/channel/nio/NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(io/netty/util/concurrent/SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(io/netty/util/internal/ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(io/netty/util/concurrent/FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java/lang/Thread.java:830)
Caused by: java.lang.ClassNotFoundException: org.slf4j.event.LoggingEvent
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2310)
        at org.jruby.javasupport.binding.MethodGatherer$1.computeValue(MethodGatherer.java:256)
        at org.jruby.javasupport.binding.MethodGatherer$1.computeValue(MethodGatherer.java:252)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
        at java.base/java.lang.ClassValue.get(ClassValue.java:114)
        at org.jruby.javasupport.binding.MethodGatherer$2.computeValue(MethodGatherer.java:266)
        at org.jruby.javasupport.binding.MethodGatherer$2.computeValue(MethodGatherer.java:263)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
        at java.base/java.lang.ClassValue.get(ClassValue.java:114)
        at org.jruby.javasupport.binding.MethodGatherer.eachAccessibleMethod(MethodGatherer.java:176)
        at org.jruby.javasupport.binding.MethodGatherer.getMethods(MethodGatherer.java:156)
        at org.jruby.javasupport.binding.MethodGatherer.setupMethods(MethodGatherer.java:558)
        at org.jruby.javasupport.binding.MethodGatherer.initialize(MethodGatherer.java:127)
        at org.jruby.javasupport.binding.ClassInitializer.initialize(ClassInitializer.java:63)
        at org.jruby.javasupport.binding.Initializer.setupProxyClass(Initializer.java:54)
        at org.jruby.javasupport.Java.createProxyClass(Java.java:549)
        at org.jruby.javasupport.Java.generateClassProxy(Java.java:507)
        at org.jruby.javasupport.Java.createProxyClassForClass(Java.java:463)
        at org.jruby.javasupport.JavaSupportImpl$3.computeValue(JavaSupportImpl.java:127)
        at org.jruby.javasupport.JavaSupportImpl$3.computeValue(JavaSupportImpl.java:119)
        at org.jruby.util.collections.MapBasedClassValue.get(MapBasedClassValue.java:25)
        at org.jruby.javasupport.JavaSupportImpl.getProxyClassFromCache(JavaSupportImpl.java:202)
        at org.jruby.javasupport.Java.getProxyClass(Java.java:430)
        at org.jruby.javasupport.Java.getInstance(Java.java:357)
        at org.jruby.javasupport.Java.getInstance(Java.java:339)
        at org.jruby.javasupport.JavaUtil.convertJavaToUsableRubyObject(JavaUtil.java:188)
        at org.jruby.javasupport.JavaMethod.convertReturn(JavaMethod.java:518)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:457)
        at org.jruby.javasupport.JavaMethod.invokeStaticDirect(JavaMethod.java:368)
        at org.jruby.java.invokers.StaticMethodInvoker.call(StaticMethodInvoker.java:42)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:375)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:174)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
        at org.jruby.ir.instructions.DefineClassInstr.INTERPRET_CLASS(DefineClassInstr.java:94)
        at org.jruby.ir.instructions.DefineClassInstr.interpret(DefineClassInstr.java:78)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.processOtherOp(StartupInterpreterEngine.java:178)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:104)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:96)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:81)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:30)
        at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
        at org.jruby.Ruby.evalScriptlet(Ruby.java:860)
        at org.jruby.Ruby.evalScriptlet(Ruby.java:836)
        at org.jruby.javasupport.JavaEmbedUtils$2.eval(JavaEmbedUtils.java:147)
        at com.artipie.gem.GemSlice.rubyLookUp(GemSlice.java:131)
        at com.artipie.gem.GemSlice.<init>(GemSlice.java:88)
        at com.artipie.gem.GemSlice.<init>(GemSlice.java:70)
        at com.artipie.SliceFromConfig.lambda$build$2(SliceFromConfig.java:92)
        at com.artipie.SliceFromConfig.lambda$build$11(SliceFromConfig.java:127)
        at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1307)
        at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1276)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
        at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
        at io.reactivex.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onComplete(SingleFlatMapPublisher.java:117)
        at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
        at io.reactivex.internal.operators.flowable.FlowableMergeWithCompletable$MergeWithSubscriber.otherComplete(FlowableMergeWithCompletable.java:120)
        at io.reactivex.internal.operators.flowable.FlowableMergeWithCompletable$MergeWithSubscriber$OtherObserver.onComplete(FlowableMergeWithCompletable.java:147)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
        at com.artipie.asto.fs.RxFile.lambda$null$0(RxFile.java:89)
        at io.vertx.reactivex.core.Future$3.handle(Future.java:190)
        at io.vertx.reactivex.core.Future$3.handle(Future.java:187)
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:159)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:120)
        at io.vertx.reactivex.core.Promise.complete(Promise.java:104)
        at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
        at io.vertx.reactivex.impl.AsyncResultCompletable.lambda$subscribeActual$0(AsyncResultCompletable.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by 0crat** [comment] 2020-05-19 14:00
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2020-05-19 15:38
@Sammers21 how did you start it, is it a docker image or jar?

**Comment by g4s8** [comment] 2020-05-25 16:38
@Sammers21 ping, no response for 6 days here

**Comment by Sammers21** [comment] 2020-05-25 18:22
@g4s8, as a jar

**Comment by g4s8** [comment] 2020-05-26 08:57
@Sammers21 what command did you use to start it?

**Comment by g4s8** [comment] 2020-06-24 07:03
@Sammers21 closing: can't reproduce

**Comment by 0crat** [comment] 2020-06-24 07:03
Job `gh:artipie/artipie#155` is not assigned, can't get performer

**Closed by g4s8** 2020-06-24 07:03 UTC
Labels: invalid

**Comment by Sammers21** [comment] 2020-06-24 07:06
@g4s8, if you can't reproduce, does it mean that there is no bug? What about asking me if the issue still present or to request more details on how to reproduce it?

**Comment by g4s8** [comment] 2020-06-25 08:44
> @g4s8, if you can't reproduce, does it mean that there is no bug? What about asking me if the issue still present or to request more details on how to reproduce it?

@Sammers21 I asked for more details one month ago: https://github.com/artipie/artipie/issues/155#issuecomment-633899457 Since you didn't answer, and I can't reproduce it, I got the conclusion that this bug is not actual anymore.
